//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public string ComplaintType { get; set; }
        public System.DateTime ComplaintTime { get; set; }
        public int ComplaintId { get; set; }
        public System.DateTime ComplaintDeadline { get; set; }
    }


    public enum ComplaintType
    {
        High,
        Medium,
        Low
    }
}
